/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExpenseCategory = IDL.Variant({
  'subscriptions' : IDL.Null,
  'other' : IDL.Null,
  'marketing' : IDL.Null,
  'travel' : IDL.Null,
  'product' : IDL.Null,
});
export const Time = IDL.Int;
export const UserId = IDL.Principal;
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'user' : UserId,
  'category' : ExpenseCategory,
  'amount' : IDL.Float64,
});
export const Sale = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'user' : UserId,
  'amount' : IDL.Float64,
  'product' : IDL.Opt(IDL.Text),
});
export const Language = IDL.Variant({
  'de' : IDL.Null,
  'en' : IDL.Null,
  'fr' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'activityType' : IDL.Text,
  'language' : Language,
  'firstName' : IDL.Text,
});
export const Month = IDL.Nat;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createExpense' : IDL.Func([IDL.Float64, ExpenseCategory], [Expense], []),
  'createSale' : IDL.Func([IDL.Float64, IDL.Opt(IDL.Text)], [Sale], []),
  'getAvailableCash' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentGoal' : IDL.Func([Month], [IDL.Float64], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getMonthlyGoalProgress' : IDL.Func(
      [IDL.Nat, Month],
      [IDL.Float64],
      ['query'],
    ),
  'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([UserProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMonthlyGoal' : IDL.Func([Month, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExpenseCategory = IDL.Variant({
    'subscriptions' : IDL.Null,
    'other' : IDL.Null,
    'marketing' : IDL.Null,
    'travel' : IDL.Null,
    'product' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserId = IDL.Principal;
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'user' : UserId,
    'category' : ExpenseCategory,
    'amount' : IDL.Float64,
  });
  const Sale = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'user' : UserId,
    'amount' : IDL.Float64,
    'product' : IDL.Opt(IDL.Text),
  });
  const Language = IDL.Variant({
    'de' : IDL.Null,
    'en' : IDL.Null,
    'fr' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'activityType' : IDL.Text,
    'language' : Language,
    'firstName' : IDL.Text,
  });
  const Month = IDL.Nat;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createExpense' : IDL.Func([IDL.Float64, ExpenseCategory], [Expense], []),
    'createSale' : IDL.Func([IDL.Float64, IDL.Opt(IDL.Text)], [Sale], []),
    'getAvailableCash' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentGoal' : IDL.Func([Month], [IDL.Float64], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getMonthlyGoalProgress' : IDL.Func(
        [IDL.Nat, Month],
        [IDL.Float64],
        ['query'],
      ),
    'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([UserProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMonthlyGoal' : IDL.Func([Month, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };