/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Expense {
  'id' : bigint,
  'date' : Time,
  'user' : UserId,
  'category' : ExpenseCategory,
  'amount' : number,
}
export type ExpenseCategory = { 'subscriptions' : null } |
  { 'other' : null } |
  { 'marketing' : null } |
  { 'travel' : null } |
  { 'product' : null };
export type Language = { 'de' : null } |
  { 'en' : null } |
  { 'fr' : null };
export type Month = bigint;
export interface Sale {
  'id' : bigint,
  'date' : Time,
  'user' : UserId,
  'amount' : number,
  'product' : [] | [string],
}
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'activityType' : string,
  'language' : Language,
  'firstName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createExpense' : ActorMethod<[number, ExpenseCategory], Expense>,
  'createSale' : ActorMethod<[number, [] | [string]], Sale>,
  'getAvailableCash' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentGoal' : ActorMethod<[Month], number>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getMonthlyGoalProgress' : ActorMethod<[bigint, Month], number>,
  'getSales' : ActorMethod<[], Array<Sale>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[UserProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setMonthlyGoal' : ActorMethod<[Month, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];